version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clashofclan
      MYSQL_DATABASE: ergophone
      MYSQL_USER: root
      MYSQL_PASSWORD: clashofclan
    ports:
      - "3306:3306"
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - .:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: clashofclan
      WORDPRESS_DB_NAME: ergophone
volumes:
  db_data: {}