version: "3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clashofclan
      MYSQL_DATABASE: ergophone
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports: 
      - "3306:3306"
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wp-config.php:/var/www/html/wp-config.php
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: ergophone

volumes:
  db_data: